// 权限对照表
export const permission = {
  // 用户管理
  'PERMISSION:USERMANAGE': '用户管理',
  'PERMISSION:USERMANAGE:USERLIST': '用户管理-用户列表',
  'PERMISSION:USERMANAGE:USERLIST:SHOW': '用户管理-用户列表-查看',
  // 账号管理
  'PERMISSION:ACCOUNTMANAGE': '账号管理',
  'PERMISSION:ACCOUNTMANAGE:ACCOUNTLIST': '账号管理-账号列表',
  'PERMISSION:ACCOUNTMANAGE:ACCOUNTLIST:SHOW': '账号管理-账号列表-查看',
  'PERMISSION:ACCOUNTMANAGE:ACCOUNTLIST:ADD': '账号管理-账号列表-新增',
  'PERMISSION:ACCOUNTMANAGE:ACCOUNTLIST:EDIT': '账号管理-账号列表-编辑',
  // 盒子BI管理
  'PERMISSION:BOXBIACCOUNTMANAGE': '盒子BI账号管理',
  'PERMISSION:BOXBIACCOUNTMANAGE:BOXBILIST': '盒子BI账号管理-账号列表',
  'PERMISSION:BOXBIACCOUNTMANAGE:BOXBILIST:SHOW': '盒子BI账号管理-账号列表-查看',
}
